// generated by stringer -type=Color; DO NOT EDIT

package color

import "fmt"

const _Color_name = "NoneWhiteBlackBlueGreenLightRedBrownPurpleOrangeYellowLightGreenCyanLightCyanLightBluePinkGrayLightGray"

var _Color_index = [...]uint8{0, 4, 9, 14, 18, 23, 31, 36, 42, 48, 54, 64, 68, 77, 86, 90, 94, 103}

func (i Color) String() string {
	i -= -1
	if i < 0 || i+1 >= Color(len(_Color_index)) {
		return fmt.Sprintf("Color(%d)", i+-1)
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}
