// Code generated by "stringer -type=PrefixFlag modes.go"; DO NOT EDIT

package modes

import "fmt"

const (
	_PrefixFlag_name_0 = "ChflPeonChflVoice"
	_PrefixFlag_name_1 = "ChflHalfop"
	_PrefixFlag_name_2 = "ChflChanop"
	_PrefixFlag_name_3 = "ChflAdmin"
	_PrefixFlag_name_4 = "ChflOwner"
)

var (
	_PrefixFlag_index_0 = [...]uint8{0, 8, 17}
	_PrefixFlag_index_1 = [...]uint8{0, 10}
	_PrefixFlag_index_2 = [...]uint8{0, 10}
	_PrefixFlag_index_3 = [...]uint8{0, 9}
	_PrefixFlag_index_4 = [...]uint8{0, 9}
)

func (i PrefixFlag) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _PrefixFlag_name_0[_PrefixFlag_index_0[i]:_PrefixFlag_index_0[i+1]]
	case i == 4:
		return _PrefixFlag_name_1
	case i == 8:
		return _PrefixFlag_name_2
	case i == 16:
		return _PrefixFlag_name_3
	case i == 32:
		return _PrefixFlag_name_4
	default:
		return fmt.Sprintf("PrefixFlag(%d)", i)
	}
}
