// Code generated by "stringer -type=SetFlag modes.go"; DO NOT EDIT

package modes

import "fmt"

const (
	_SetFlag_name_0 = "SetNoneSetKey"
	_SetFlag_name_1 = "SetForward"
	_SetFlag_name_2 = "SetLimit"
	_SetFlag_name_3 = "SetJoinThrottle"
)

var (
	_SetFlag_index_0 = [...]uint8{0, 7, 13}
	_SetFlag_index_1 = [...]uint8{0, 10}
	_SetFlag_index_2 = [...]uint8{0, 8}
	_SetFlag_index_3 = [...]uint8{0, 15}
)

func (i SetFlag) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _SetFlag_name_0[_SetFlag_index_0[i]:_SetFlag_index_0[i+1]]
	case i == 4:
		return _SetFlag_name_1
	case i == 8:
		return _SetFlag_name_2
	case i == 16:
		return _SetFlag_name_3
	default:
		return fmt.Sprintf("SetFlag(%d)", i)
	}
}
