// Code generated by "stringer -type=UserFlag modes.go"; DO NOT EDIT

package modes

import "fmt"

const _UserFlag_name = "UPropNoneUPropInvisibleUPropCalleridUPropIrcopUPropCloakedUPropAdminUPropOverrideUPropNoCTCPUPropDeafUPropDisforwardUPropRegpmUPropSoftcallUPropNoinviteUPropNostalkUPropSSLClientUPropNetworkService"

var _UserFlag_map = map[UserFlag]string{
	1:     _UserFlag_name[0:9],
	2:     _UserFlag_name[9:23],
	4:     _UserFlag_name[23:36],
	8:     _UserFlag_name[36:46],
	16:    _UserFlag_name[46:58],
	32:    _UserFlag_name[58:68],
	64:    _UserFlag_name[68:81],
	128:   _UserFlag_name[81:92],
	256:   _UserFlag_name[92:101],
	512:   _UserFlag_name[101:116],
	1024:  _UserFlag_name[116:126],
	2048:  _UserFlag_name[126:139],
	4096:  _UserFlag_name[139:152],
	8192:  _UserFlag_name[152:164],
	16384: _UserFlag_name[164:178],
	32768: _UserFlag_name[178:197],
}

func (i UserFlag) String() string {
	if str, ok := _UserFlag_map[i]; ok {
		return str
	}
	return fmt.Sprintf("UserFlag(%d)", i)
}
