// generated by stringer -type=PrefixFlag; DO NOT EDIT

package modes

import "fmt"

const _PrefixFlag_name = "ChflPeonChflVoiceChflHalfopChflChanopChflAdminChflOwner"

var _PrefixFlag_index = [...]uint8{0, 8, 17, 27, 37, 46, 55}

func (i PrefixFlag) String() string {
	if i < 0 || i+1 >= PrefixFlag(len(_PrefixFlag_index)) {
		return fmt.Sprintf("PrefixFlag(%d)", i)
	}
	return _PrefixFlag_name[_PrefixFlag_index[i]:_PrefixFlag_index[i+1]]
}
