// generated by stringer -type=PropFlag; DO NOT EDIT

package modes

import "fmt"

const _PropFlag_name = "PropNonePropMutePropPrivatePropInvitePropTopicrestPropInternalPropSecretPropNoCTCPPropNoActionPropNoKicksPropNoCapsPropNoRejoinPropLargelistPropNoOperKickPropOperonlyPropPermanentPropDisforwardPropNoNoticePropNoColorPropNoNicksPropFreeinvitePropHidebansPropOpmodPropFreefwdPropNoRepeat"

var _PropFlag_index = [...]uint16{0, 8, 16, 27, 37, 50, 62, 72, 82, 94, 105, 115, 127, 140, 154, 166, 179, 193, 205, 216, 227, 241, 253, 262, 273, 285}

func (i PropFlag) String() string {
	if i < 0 || i+1 >= PropFlag(len(_PropFlag_index)) {
		return fmt.Sprintf("PropFlag(%d)", i)
	}
	return _PropFlag_name[_PropFlag_index[i]:_PropFlag_index[i+1]]
}
