// generated by stringer -type=SetFlag; DO NOT EDIT

package modes

import "fmt"

const _SetFlag_name = "SetNoneSetKeySetForwardSetLimitSetJoinThrottle"

var _SetFlag_index = [...]uint8{0, 7, 13, 23, 31, 46}

func (i SetFlag) String() string {
	if i < 0 || i+1 >= SetFlag(len(_SetFlag_index)) {
		return fmt.Sprintf("SetFlag(%d)", i)
	}
	return _SetFlag_name[_SetFlag_index[i]:_SetFlag_index[i+1]]
}
