package numeric

var formatStrings map[Response]string

func init() {
	formatStrings = map[Response]string{
		Response("001"): ":Welcome to the %s Internet Relay Chat Network %s",
		Response("002"): ":Your host is %s, running version %s",
		Response("003"): ":This server was created %s",
		Response("004"): "%s %s %s %s %s",
		Response("005"): "%s :are supported by this server",
		Response("008"): "%s :Server notice mask",
		Response("010"): "%s %d :Please use this Server/Port instead",
		Response("015"): ":%s",
		Response("017"): ":End of /MAP",
		Response("043"): "%s :Nick collision, forcing nick change to your unique ID",
		Response("200"): "Link %s %s %s",
		Response("201"): "Try. %s %s",
		Response("202"): "H.S. %s %s",
		Response("203"): "???? %s %s (%s) %d",
		Response("204"): "Oper %s %s (%s) %lu %lu",
		Response("205"): "User %s %s (%s) %lu %lu",
		Response("206"): "Serv %s %dS %dC %s %s!%s@%s %lu",
		Response("208"): "<newtype> 0 %s",
		Response("209"): "Class %s %d",
		Response("212"): "%s %u %u :%u",
		Response("213"): "C %s %s %s %d %s",
		Response("215"): "I %s %s %s@%s %d %s",
		Response("216"): "%c %s * %s :%s%s%s",
		Response("217"): "%c %d %s :%s",
		Response("218"): "Y %s %d %d %d %u %d.%d %d.%d %u",
		Response("219"): "%c :End of /STATS report",
		Response("220"): "%c %d %s %d :%s%s",
		Response("221"): "%s",
		Response("225"): "%c %s :%s%s%s",
		Response("241"): "L %s * %s 0 -1",
		Response("242"): ":Server Up %d days, %d:%02d:%02d",
		Response("243"): "o %s@%s * %s %s %s",
		Response("244"): "H %s * %s 0 -1",
		Response("247"): "%c %d %s :%s",
		Response("248"): "U %s %s@%s %s",
		Response("250"): ":Highest connection count: %d (%d clients) (%d connections received)",
		Response("251"): ":There are %d users and %d invisible on %d servers",
		Response("252"): "%d :IRC Operators online",
		Response("253"): "%d :unknown connection(s)",
		Response("254"): "%d :channels formed",
		Response("255"): ":I have %d clients and %d servers",
		Response("256"): ":Administrative info about %s",
		Response("257"): ":%s",
		Response("258"): ":%s",
		Response("259"): ":%s",
		Response("262"): "%s :End of TRACE",
		Response("263"): ":%s 263 %s %s :This command could not be completed because it has been used recently, and is rate-limited.",
		Response("265"): "%d %d :Current local users %d, max %d",
		Response("266"): "%d %d :Current global users %d, max %d",
		Response("270"): "%s :%s",
		Response("276"): "%s :has client certificate fingerprint %s",
		Response("281"): ":%s 281 %s %s",
		Response("282"): ":%s 282 %s :End of /ACCEPT list.",
		Response("301"): "%s :%s",
		Response("302"): ":%s 302 %s :%s",
		Response("303"): ":%s 303 %s :",
		Response("305"): ":You are no longer marked as being away",
		Response("306"): ":You have been marked as being away",
		Response("311"): "%s %s %s * :%s",
		Response("312"): "%s %s :%s",
		Response("313"): "%s :%s",
		Response("314"): ":%s 314 %s %s %s %s * :%s",
		Response("315"): ":%s 315 %s %s :End of /WHO list.",
		Response("317"): "%s %d %d :seconds idle, signon time",
		Response("318"): "%s :End of /WHOIS list.",
		Response("319"): ":%s 319 %s %s :",
		Response("321"): ":%s 321 %s Channel :Users  Name",
		Response("322"): ":%s 322 %s %s%s %d :%s",
		Response("323"): ":%s 323 %s :End of /LIST",
		Response("324"): ":%s 324 %s %s %s",
		Response("325"): ":%s 325 %s %s %s :is the current channel mode-lock",
		Response("329"): ":%s 329 %s %s %lu",
		Response("330"): "%s %s :is logged in as",
		Response("331"): ":%s 331 %s %s :No topic is set.",
		Response("332"): ":%s 332 %s %s :%s",
		Response("333"): ":%s 333 %s %s %s %lu",
		Response("335"): "%s :is a bot",
		Response("338"): "%s %s :actually using host",
		Response("341"): ":%s 341 %s %s %s",
		Response("346"): ":%s 346 %s %s %s %s %lu",
		Response("347"): ":%s 347 %s %s :End of Channel Invite List",
		Response("348"): ":%s 348 %s %s %s %s %lu",
		Response("349"): ":%s 349 %s %s :End of Channel Exception List",
		Response("351"): "%s(%s). %s :%s TS%dow %s",
		Response("352"): ":%s 352 %s %s %s %s %s %s %s :%d %s",
		Response("353"): ":%s 353 %s %s %s :",
		Response("360"): ":%s 360 %s %s :was connecting from *@%s %s",
		Response("362"): ":%s 362 %s %s :Closed. Status = %d",
		Response("363"): ":%s 363 %s %d :Connections Closed",
		Response("364"): "%s %s :%d %s",
		Response("365"): "%s :End of /LINKS list.",
		Response("366"): ":%s 366 %s %s :End of /NAMES list.",
		Response("367"): ":%s 367 %s %s %s %s %lu",
		Response("368"): ":%s 368 %s %s :End of Channel Ban List",
		Response("369"): ":%s 369 %s %s :End of WHOWAS",
		Response("371"): ":%s",
		Response("372"): ":%s 372 %s :- %s",
		Response("374"): ":End of /INFO list.",
		Response("375"): ":%s 375 %s :- %s Message of the Day - ",
		Response("376"): ":%s 376 %s :End of /MOTD command.",
		Response("378"): "%s :is connecting from *@%s %s",
		Response("379"): "%s :is using modes %s",
		Response("381"): ":%s 381 %s :Making sense? Aw, what fun is there in making sense?",
		Response("382"): ":%s 382 %s %s :Rehashing",
		Response("386"): ":%s 386 %s :%s",
		Response("391"): "%s :%s",
		Response("401"): "%s :No such nick/channel",
		Response("402"): "%s :No such server",
		Response("403"): "%s :No such channel",
		Response("404"): "%s :Cannot send to channel",
		Response("405"): ":%s 405 %s %s :You have joined too many channels",
		Response("406"): ":%s 406 %s %s :There was no such nickname",
		Response("407"): ":%s 407 %s %s :Too many recipients.",
		Response("409"): ":%s 409 %s :No origin specified",
		Response("410"): ":%s 410 %s %s :Invalid CAP subcommand",
		Response("411"): ":%s 411 %s :No recipient given (%s)",
		Response("412"): ":%s 412 %s :No text to send",
		Response("413"): "%s :No toplevel domain specified",
		Response("414"): "%s :Wildcard in toplevel Domain",
		Response("416"): ":%s 416 %s %s :output too large, truncated",
		Response("421"): ":%s 421 %s %s :Unknown command",
		Response("422"): ":%s 422 %s :MOTD File is missing",
		Response("431"): ":%s 431 %s :No nickname given",
		Response("432"): ":%s 432 %s %s :Erroneous Nickname",
		Response("433"): ":%s 433 %s %s :Nickname is already in use.",
		Response("435"): "%s %s :Cannot change nickname while banned on channel",
		Response("436"): "%s :Nickname collision KILL",
		Response("437"): ":%s 437 %s %s :Nick/channel is temporarily unavailable",
		Response("438"): ":%s 438 %s %s %s :Nick change too fast. Please wait %d seconds.",
		Response("440"): "%s :Services are currently unavailable",
		Response("441"): "%s %s :They aren't on that channel",
		Response("442"): "%s :You're not on that channel",
		Response("443"): "%s %s :is already on channel",
		Response("447"): ":Can't send invite to %s (+V set)",
		Response("449"): "%s :Cannot change nickname while on channel (+d set)",
		Response("451"): ":%s 451 * :You have not registered",
		Response("456"): ":%s 456 %s :Accept list is full",
		Response("457"): ":%s 457 %s %s :is already on your accept list",
		Response("458"): ":%s 458 %s %s :is not on your accept list",
		Response("461"): ":%s 461 %s %s :Not enough parameters",
		Response("462"): ":%s 462 %s :You may not reregister",
		Response("464"): ":%s 464 %s :Password Incorrect",
		Response("465"): ":%s 465 %s :You are banned from this server- %s",
		Response("470"): "%s %s :Forwarding to another channel",
		Response("471"): ":%s 471 %s %s :Cannot join channel (+l) - channel is full, try again later",
		Response("472"): ":%s 472 %s %c :is an unknown mode char to me",
		Response("473"): ":%s 473 %s %s :Cannot join channel (+i) - you must be invited",
		Response("474"): ":%s 474 %s %s :Cannot join channel (+b) - you are banned",
		Response("475"): ":%s 475 %s %s :Cannot join channel (+k) - bad key",
		Response("477"): ":%s 477 %s %s :Cannot join channel (+r) - you need to be identified with services",
		Response("478"): ":%s 478 %s %s %s :Channel ban list is full",
		Response("479"): "%s :Illegal channel name",
		Response("480"): ":%s 480 %s %s :Cannot join channel (+j) - throttle exceeded, try again later",
		Response("481"): ":Permission Denied - You're not an IRC operator",
		Response("482"): ":%s 482 %s %s :You're not a channel operator",
		Response("483"): ":You can't kill a server!",
		Response("484"): ":%s 484 %s %s %s :Cannot kick or deop a network service",
		Response("486"): "%s :You must log in with services to message this user",
		Response("489"): ":%s 489 %s %s :You're neither voiced nor channel operator",
		Response("491"): ":Operator authentication failed",
		Response("492"): ":Can't send CTCP to %s (+C set)",
		Response("494"): "%s :cannot answer you while you are %s, your message was not sent",
		Response("495"): ":%s 495 %s %s :Cannot rejoin channel so soon after being kicked (+J set)",
		Response("501"): ":%s 501 %s :Unknown MODE flag",
		Response("502"): ":%s 502 %s :Can't change mode for other users",
		Response("504"): ":%s 504 %s %s :User is not on this server",
		Response("513"): ":%s 513 %s :To connect type /QUOTE PONG %08lX",
		Response("517"): "%s :This command has been administratively disabled",
		Response("519"): "%s :You cannot kick users in this channel because +E is set",
		Response("524"): ":%s 524 %s %s :Help not found",
		Response("671"): "%s :is using a secure connection",
		Response("672"): "%s :is using a web IRC client",
		Response("702"): ":%s 702 %s %s 0x%x %s %s",
		Response("703"): ":%s 703 %s :End of /MODLIST.",
		Response("704"): ":%s 704 %s %s :%s",
		Response("705"): ":%s 705 %s %s :%s",
		Response("706"): ":%s 706 %s %s :End of /HELP.",
		Response("707"): ":%s 707 %s %s :Targets changing too fast, message dropped",
		Response("708"): ":%s 708 %s %s %s %s %s %s %s %s :%s",
		Response("709"): ":%s 709 %s %s %s %s %s %s %s :%s",
		Response("710"): ":%s 710 %s %s %s!%s@%s :has asked for an invite.",
		Response("711"): ":%s 711 %s %s :Your KNOCK has been delivered.",
		Response("712"): ":%s 712 %s %s :Too many KNOCKs (%s).",
		Response("713"): "%s :Channel is open.",
		Response("714"): ":%s 714 %s %s :You are already on that channel.",
		Response("715"): ":%s 715 %s :KNOCKs are disabled.",
		Response("716"): "%s :is in +g mode (server-side ignore.)",
		Response("717"): "%s :has been informed that you messaged them.",
		Response("718"): ":%s 718 %s %s %s@%s :is messaging you, and you have umode +g. To accept messages from this person, use /ACCEPT %s",
		Response("720"): ":%s 720 %s :Start of OPER MOTD",
		Response("721"): ":%s 721 %s :%s",
		Response("722"): ":%s 722 %s :End of OPER MOTD",
		Response("723"): ":%s 723 %s %s :Insufficient oper privs",
		Response("725"): ":%s 725 %s %c %ld %s :%s",
		Response("726"): ":%s 726 %s %s :No matches",
		Response("727"): ":%s 727 %s %d %d %s!%s@%s %s :Local/remote clients match",
		Response("728"): ":%s 728 %s %s q %s %s %lu",
		Response("729"): ":%s 729 %s %s q :End of Channel Quiet List",
		Response("730"): ":%s 730 %s :%s",
		Response("731"): ":%s 731 %s :%s",
		Response("732"): ":%s 732 %s :%s",
		Response("733"): ":%s 733 %s :End of MONITOR list",
		Response("734"): ":%s 734 %s %d %s :Monitor list is full",
		Response("737"): "%s :is in +G mode (server-side ignore) and you do not share a common channel with them.",
		Response("740"): ":%s 740 %s :%s",
		Response("741"): ":%s 741 %s :End of CHALLENGE",
		Response("742"): "%s %c %s :MODE cannot be set due to channel having an active MLOCK restriction policy",
		Response("750"): "%d :matches",
		Response("751"): "%s %s %s %s %s %s :%s",
		Response("900"): ":%s 900 %s %s!%s@%s %s :You are now logged in as %s.",
		Response("901"): ":%s 901 %s %s!%s@%s :You are now logged out.",
		Response("902"): ":%s 902 %s :You must use a nick assigned to you.",
		Response("903"): ":%s 903 %s :SASL authentication successful",
		Response("904"): ":%s 904 %s :SASL authentication failed",
		Response("905"): ":%s 905 %s :SASL message too long",
		Response("906"): ":%s 906 %s :SASL authentication aborted",
		Response("907"): ":%s 907 %s :You have already completed SASL authentication",
	}
}
