// Code generated by "stringer -type=Type"; DO NOT EDIT

package events

import "fmt"

const _Type_name = "EvNoneEvAcceptAddEvAcceptRemoveEvAcceptListEvAdminEvAwaySetReasonEvAwayClearReasonEvChghostEvDlineAddEvDlineTestEvDlineRemoveEvHelpEvInviteEvJoinEvKickEvKillEvKlineAddEvKlineTestEvKlineRemoveEvKnockEvListEvChannelModeAddEvChannelModeQueryEvChannelModeRemoveEvChannelListAddEvChannelListQueryEvChannelListRemoveEvMonitorAddEvMonitorRemoveEvMonitorClearEvMonitorQueryEvMonitorStatusEvMotdEvNamesEvNickEvNoticeChannelEvNoticeUserEvPartChannelEvPassEvPingEvMessageChannelEvMessageUserEvQuitEvResvChannelAddEvResvChannelQueryEvResvChannelRemoveEvResvNickAddEvResvNickQueryEvResvNickRemoveEvTopicEvUserEvUsersEvVersionEvWhoChannelEvWhoUserEvWhoisEvWhowasEvGecosBanAddEvGecosBanQueryEvGecosBanRemove"

var _Type_index = [...]uint16{0, 6, 17, 31, 43, 50, 65, 82, 91, 101, 112, 125, 131, 139, 145, 151, 157, 167, 178, 191, 198, 204, 220, 238, 257, 273, 291, 310, 322, 337, 351, 365, 380, 386, 393, 399, 414, 426, 439, 445, 451, 467, 480, 486, 502, 520, 539, 552, 567, 583, 590, 596, 603, 612, 624, 633, 640, 648, 661, 676, 692}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
